# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-22 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20171118_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(upload_to='org/%Y/%m', verbose_name='\u5c01\u9762\u56fe'),
        ),
    ]
