# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-01 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20171122_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='image/defult.png', upload_to='upload/iamge/%Y/%m'),
        ),
    ]
